### PR TITLE
Rename flag testDebug to debugger

### PR DESCRIPTION
**Pull request by neworld**
**Problem:** flag `testDebug` clash with default android flavor #41
**Solution:** rename `testDebug` to `debugger` (as suggest @nenick)

This is better alternative for #40 because it don't break experience for CLI lovers.

Do not forget update wiki.

### CODE REVIEW

**Comment by blundell** [comment]
this seems to resolved the argument happening in #40 :+1:

**Comment by nenick** [comment]
Reasons that this PR will not get merged? Please also create a new release.

**Comment by neworld** [comment]
ping

**Comment by blundell** [comment]
pong

**Pull request merged**
