### PR TITLE
Add debug property

### PR DESCRIPTION
**Pull request by neworld**
**Problem**: Sometimes is hard to find what is wrong with tests
**Solution**: Use debug

How this is working:

1. First you need to enable debug mode `./gradlew -PtestDebug=true` 
2. Wait until tests will be ready and gradle waits for debugger
3. Make sure you have [remote debug](https://cloud.githubusercontent.com/assets/38703/5818871/bb6e146a-a0c1-11e4-8f73-49616e707c8f.png) configuration on 5005 port
4. start debugging: image

Of course you should have been added some breakpoints.

Happy debugging!

### CODE REVIEW

**Comment by neworld** [comment]
Ping

**Comment by blundell** [comment]
:+1:

**Comment by xrigau** [comment]
Hi @neworld 

Thanks very much for your PR!! Much appreciated. I'll let you know once this change gets released

**Comment by neworld** [comment]
Thanks for review :ok_hand:

**Comment by xrigau** [comment]
nice PR description btw!

**Comment by xrigau** [comment]
I've added your description to the wiki page: https://github.com/novoda/gradle-android-test-plugin/wiki/JVM-options-that-can-be-passed-in

Version 0.10.2 includes this change and it has been released to jcenter: https://bintray.com/novoda/maven/gradle-android-test-plugin/0.10.2/view

Thanks @neworld !

**Comment by neworld** [comment]
Thanks for you, made my life much easier

**Comment by xrigau** [comment]
:smile_cat:

**Comment by nenick** [comment]
This will not work with anymore with android gradle build tools 1.1.0. I like to remove this lines to support newest versions

Why you don't use Android Studio to debug your tests?

**Comment by nenick** [comment]
If you don't know how to run this tests inside Android Studio please read this guide https://github.com/nenick/android-gradle-template/wiki/Tests-in-Android-Studio---IntellJ

**Comment by neworld** [comment]
You way is to much complicated since sometimes need restart IDE or press `test` again due bugs or maybe incompatible usage. In my personal point of view, I prefer use CLI instead IDE and don't like be forced to use a mouse more.

So I suggest to have both ways for all kind of people

**Comment by nenick** [comment]
I don't see issues with the explained way. My co workers don't have issues and some companies I had helped haven't issues too. But this lines force us all to use a custom version of this plugin when we don't have a flavor project setup.

**Pull request merged**
