### PR TITLE
Fix #37 Expose variants in DSL

### LINKED ISSUE #37: Expose variants as part of the plugin DSL
This would be just like in the Android Gradle plugin and allow the same level of task manipulation

Ex:
```
android.variants.each { variant ->
    ....
}
```

### PR DESCRIPTION
**Pull request by baolongnt**
Fixes #37

### CODE REVIEW

**Comment by blundell** [comment]
Seems legit to me, @devisnik do you have architectural / security questions? else :shipit:

**Comment by devisnik** [comment]
LGTM.
I'm wondering how this would be used though, after all the variants can be easily derived directly from the android project. May be @baolongnt can add some example use case?

**Comment by baolongnt** [comment]
I am augmenting my build script with a bunch of custom tasks and it's much more elegant to get access to the variants within the android{} closure than doing something like this:
```
def projectUnderTestName = ':app'

android {
    projectUnderTest projectUnderTestName
}

project(projectUnderTestName).android.applicationVariants.all { variant -> 
...
}
```

With the code from my PR
```
android {
    projectUnderTest ':app'

    variants.all { variant -> 
    ...
    }
}
```

Note: I am almost done with getting Jacoco working. Let me know if you are interested in a PR for that.

**Comment by devisnik** [comment]
:+1:

**Pull request merged**
